### ISSUE TITLE
Login not authorized 

### ISSUE THREAD

**Issue by RamazanGeven** [500Foods/TMS-XData-TemplateDemoData#3]
SystemServiceImplementation.pas

  //if Query1.FieldByName('role_id').AsInteger <> 0 then raise EXDataHttpUnauthorized.Create('Login not authorized');
  if Query1.RecordCount< 1 then raise EXDataHttpUnauthorized.Create('Login not authorized(Rol YOK)');

**Comment by 500Foods** [comment]
This might not actually be correct.  

Roles are intended to reflect various functions or features that may be assigned to a person.  Could be used in different ways of course, but a given person may have several roles assigned to them.

This check is to see if, specifically, they have role #0.  This is setup at the moment as the "Login" role - you need this role to be able to login.  Someone might have this revoked if they're on extended leave, or if they've left the organization, or are no longer a client or whatever the case may be.  So other roles may be present.
